[Forma]
Clave=ACD00022ZonasAgentes
Nombre=Zonas Agentes
Icono=67
VentanaTipoMarco=Normal
Modulos=(Todos)
ListaCarpetas=zonasAgentes
CarpetaPrincipal=zonasAgentes
PosicionInicialAlturaCliente=459
PosicionInicialAncho=501
VentanaPosicionInicial=por Dise�o
VentanaBloquearAjuste=S
VentanaEstadoInicial=Normal
ExpresionesAlMostrar=EjecutarSQL(<T>EXEC SP_ACD00022CargarZonasAgentes<T>)
[zonasAgentes]
Estilo=Hoja
VentanaTipoMarco=Normal
Clave=zonasAgentes
FichaColorFondo=Negro
PermiteEditar=S
AlineacionAutomatica=S
AcomodarTexto=S
MostrarConteoRegistros=S
Zona=A1

Vista=ACD00022ZonasAgentes
Fuente={Tahoma, 8, Negro, []}
HojaTitulos=S
HojaMostrarColumnas=S
HojaMostrarRenglones=S
HojaColoresPorEstatus=S
HojaPermiteInsertar=S
HojaPermiteEliminar=S
HojaVistaOmision=Autom�tica
CampoColorLetras=Negro
CampoColorFondo=Blanco
ListaEnCaptura=ACD00022ZonasAgentes.Agente<BR>ACD00022ZonasAgentes.Nombre<BR>ACD00022ZonasAgentes.zona
CarpetaVisible=S
[zonasAgentes.Columnas]
Agente=64
Nombre=258
zona=137
[zonasAgentes.ACD00022ZonasAgentes.Agente]
Carpeta=zonasAgentes
Clave=ACD00022ZonasAgentes.Agente
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=10
ColorFondo=Blanco
ColorFuente=Negro
[zonasAgentes.ACD00022ZonasAgentes.Nombre]
Carpeta=zonasAgentes
Clave=ACD00022ZonasAgentes.Nombre
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=100
ColorFondo=Blanco
ColorFuente=Negro
[zonasAgentes.ACD00022ZonasAgentes.zona]
Carpeta=zonasAgentes
Clave=ACD00022ZonasAgentes.zona
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=50
ColorFondo=Blanco
ColorFuente=Negro
