[Forma]
Clave=CobTelResp1Mavi
ListaCarpetas=Resp1<BR>cuantos
Nombre=Respuesta
VentanaTipoMarco=Normal
Icono=0
[Resp1]
Estilo=Ficha
Clave=Resp1
FichaColorFondo=Negro
Zona=B1
[Resp1.CobTelMavi.FechaPromesa]
Carpeta=Resp1
[Resp1.CobTelMavi.MontoPromesa]
Carpeta=Resp1
[cuantos]
Estilo=Ficha
FichaColorFondo=Negro
Zona=A1
[cuantos.Info.Numero]
Carpeta=cuantos
Clave=Info.Numero
Editar=S