[Forma]
(�|�|�|�|�|�)
Clave=VentaValeMAVILista
Nombre=<T>Vales - <T>+SQL(<T>SELECT Mov FROM Venta WHERE ID=:nID<T>, Info.IDMAVI)+<T> <T>+SQL(<T>SELECT MovID FROM Venta WHERE ID=:nID<T>, Info.IDMAVI)
Icono=0
BarraHerramientas=S
Modulos=(Todos)
AccionesTamanoBoton=15x5
AccionesDerecha=S
ListaAcciones=Salir
ListaCarpetas=Lista
CarpetaPrincipal=Lista
PosicionInicialIzquierda=279
PosicionInicialArriba=279
PosicionInicialAlturaCliente=273
PosicionInicialAncho=297
MovModulo=(Todos)
VentanaTipoMarco=Normal
VentanaPosicionInicial=por Dise�o
VentanaExclusiva=S
[Acciones.Salir]
Nombre=Salir
Boton=23
NombreEnBoton=S
NombreDesplegar=&Salir
EnBarraHerramientas=S
TipoAccion=Ventana
ClaveAccion=Cerrar
Activo=S
Visible=S
[Lista]
Estilo=Hoja
Clave=Lista
Filtros=S
AlineacionAutomatica=S
AcomodarTexto=S
MostrarConteoRegistros=S
Zona=A1
Vista=VentaValeMAVI
Fuente={Tahoma, 8, Negro, []}
CampoColorLetras=Negro
CampoColorFondo=Blanco
ListaEnCaptura=VentaValeMAVI.Vale
FiltroPredefinido=S
FiltroNullNombre=(sin clasificar)
FiltroEnOrden=S
FiltroTodoNombre=(Todo)
FiltroAncho=20
FiltroRespetar=S
FiltroTipo=General
CarpetaVisible=S
HojaTitulos=S
HojaMostrarColumnas=S
HojaMostrarRenglones=S
HojaColoresPorEstatus=S
HojaPermiteInsertar=S
HojaPermiteEliminar=S
HojaVistaOmision=Autom�tica
FiltroGeneral=VentaValeMAVI.ID ={Info.IDMAVI}
[Lista.VentaValeMAVI.Vale]
Carpeta=Lista
Clave=VentaValeMAVI.Vale
Editar=S
LineaNueva=S
ValidaNombre=S
3D=S
Tamano=20
ColorFondo=Blanco
ColorFuente=Negro
[Lista.Columnas]
Vale=251
